name = "medium-server"
compatibility_date = "2025-05-11"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMDFKWEY5SFJXS0Y5TldGOE1BNzZHTkdZWEEiLCJ0ZW5hbnRfaWQiOiIxYzY2NzEzNmI5ODQ5NzdkMjRlZTE5OGQ1ZmNmZGVlNGFkZTUwNjdiMmNhN2Y1ZjFiODM1OWIwYjNlZDdiMjllIiwiaW50ZXJuYWxfc2VjcmV0IjoiNDFkMDA4NWQtZGViMC00NTkwLWI3MmEtYzgyZjIxOWEyZGZlIn0.7gE9Z3kfjLB8F7srFXDggH9MNWXrUAMBXr_UfENkxMs"
JWT_SECRET="123567890986432"